#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
project_dir="$(cd -- "${script_dir}/.." && pwd)"
python_bin="${project_dir}/.venv/bin/python"
voice_dir="${project_dir}/voices"
config_file="${project_dir}/.tts.conf"

if [[ ! -f "${config_file}" ]]; then
    printf 'Fout: geen stem geconfigureerd. Voer eerst %s/scripts/setup.sh uit.\n' "${project_dir}" >&2
    exit 1
fi

# This local file is generated by setup.sh and contains only VOICE_NAME.
# shellcheck disable=SC1090
source "${config_file}"

if [[ -z "${VOICE_NAME-}" ]] || [[ ! "${VOICE_NAME}" =~ ^[A-Za-z0-9_-]+$ ]]; then
    printf 'Fout: ongeldige VOICE_NAME in %s.\n' "${config_file}" >&2
    exit 1
fi

model_file="${voice_dir}/${VOICE_NAME}.onnx"

sentence_silence=""
if [[ "${1-}" == "--sentence-silence" ]]; then
    if (( $# < 2 )) || [[ ! "$2" =~ ^[0-9]+([.][0-9]+)?$ ]]; then
        printf 'Fout: --sentence-silence verwacht een aantal seconden.\n' >&2
        exit 2
    fi
    sentence_silence="$2"
    shift 2
fi

if [[ "${1-}" == "--text" ]]; then
    shift
    text="$*"
elif (( $# == 0 )); then
    text="$(cat)"
else
    printf 'Gebruik: %s [--sentence-silence SECONDEN] [--text TEKST]\n' "$0" >&2
    exit 2
fi

if [[ ! "${text}" =~ [^[:space:]] ]]; then
    exit 0
fi

# Acronyms benefit from spelling with both the Dutch and English voices.
pronunciation_dictionary=(
    "HTTPS|H T T P S"
    "HTTP|H T T P"
    "JSON|J S O N"
    "API|A P I"
    "LAN|lan"
    "URL|U R L"
)

# The Dutch voice needs help with English security terminology and mixed Dutch-
# English compounds. Keep longer and plural forms before their shorter roots.
if [[ "${VOICE_NAME}" == nl_* ]]; then
    pronunciation_dictionary=(
    "frameworkindicaties|freem-wurk-indicaties"
    "technologie-indicaties|technologie-indicaties"
    "browserweergave|brauwzer-weergave"
    "netwerkrequests|netwerk-rie-kwests"
    "securityheaders|sie-kjuh-rie-tieh, hedders"
    "responseheaders|rie-spons-hedders"
    "responsebody|rie-spons-boddie"
    "HTTP-response|H T T P rie-spons"
    "HTTP-headers|H T T P hedders"
    "Content-Type|kontent-taip"
    "Juice Shop-server|djoes sjop. sur-vur"
    "Juice Shop|djoes sjop"
    "labtargets|lab-tahr-kets"
    "Playwright|pleejwreit"
    "Docker|dokker"
    "labtarget|lab-tahr-ket"
    "target|tahr-ket"
    "beginnerstutorial|beginners-tutoriál"
    "web-enumeration|web-ie-noe-me-ree-sjun"
    "webapplicatie|web-applicatie"
    "tutorial|tjoe-toorie-el"
    "headers|hedders"
    "header|hedder"
    "framework|freem-wurk"
    "services|sur-visses"
    "service|sur-vis"
    "hosts|hoosts"
    "host|hoost"
    "server|sur-vur"
    "scope|skoop"
    "waarnemen|waar-neemen"
    "browsers|brauwzers"
    "browser|brauwzer"
    "requests|rie-kwests"
    "request|rie-kwest"
    "endpoints|end-points"
    "endpoint|end-point"
    "JavaScript|djaa-va-skript"
    "Nmap|en-map"
    "enumeration|ie-noe-me-ree-sjun"
    "payloads|pee-loowds"
    "payload|pee-loowd"
    "exploits|eks-plojts"
    "exploit|eks-plojt"
    "shells|sjels"
    "shell|sjel"
    "localhost|loo-kel-hoost"
    "curl|kurl"
    "Piper|paiper"
    "${pronunciation_dictionary[@]}"
    )
fi

replace_spoken_term() {
    local source="$1"
    local term="$2"
    local replacement="$3"
    local result=""
    local match
    local prefix

    shopt -s nocasematch
    while [[ "${source}" =~ (^|[^[:alnum:]_])(${term})([^[:alnum:]_]|$) ]]; do
        match="${BASH_REMATCH[0]}"
        prefix="${source%%"${match}"*}"
        result+="${prefix}${BASH_REMATCH[1]}${replacement}${BASH_REMATCH[3]}"
        source="${source#*"${match}"}"
    done

    printf '%s' "${result}${source}"
}

for dictionary_entry in "${pronunciation_dictionary[@]}"; do
    written_term="${dictionary_entry%%|*}"
    spoken_form="${dictionary_entry#*|}"
    text="$(replace_spoken_term "${text}" "${written_term}" "${spoken_form}")"
done

if [[ ! -x "${python_bin}" ]]; then
    printf 'Fout: Piper-omgeving niet gevonden. Voer eerst %s/scripts/setup.sh uit.\n' "${project_dir}" >&2
    exit 1
fi

if [[ ! -f "${model_file}" ]]; then
    printf 'Fout: Piper-model niet gevonden: %s\n' "${model_file}" >&2
    exit 1
fi

if ! command -v pw-play >/dev/null 2>&1; then
    printf 'Fout: pw-play is niet gevonden.\n' >&2
    exit 1
fi

tts_worker='
    set -o errexit
    set -o nounset
    set -o pipefail

    text="$1"
    python_bin="$2"
    model_file="$3"
    sentence_silence="$4"

    sleep 1

    wav_file="$(mktemp --suffix=.wav)"
    cleanup() {
        rm -f -- "${wav_file}"
    }
    trap cleanup EXIT
    trap "exit 129" HUP
    trap "exit 130" INT
    trap "exit 143" TERM

    piper_options=(
        --model "${model_file}"
        --output_file "${wav_file}"
    )
    if [[ -n "${sentence_silence}" ]]; then
        piper_options+=(--sentence-silence "${sentence_silence}")
    fi

    printf "%s\n" "${text}" | "${python_bin}" -m piper "${piper_options[@]}"

    pw-play -- "${wav_file}"
'

# A transient user service survives the short-lived Codex command runner. It is
# automatically collected after playback. Fall back to nohup in environments
# without a usable systemd user session, such as some standalone terminals.
if systemd-run --user --collect --quiet \
    --expand-environment=no \
    --property=Type=exec \
    --property=StandardInput=null \
    --property=StandardOutput=null \
    --property=StandardError=null \
    bash -c "${tts_worker}" speak-background \
    "${text}" "${python_bin}" "${model_file}" "${sentence_silence}" \
    >/dev/null 2>&1; then
    exit 0
fi

nohup bash -c "${tts_worker}" speak-background \
    "${text}" "${python_bin}" "${model_file}" "${sentence_silence}" \
    </dev/null >/dev/null 2>&1 &
